### ISSUE TITLE
Inaccessible ErrorObject params in TypeScript

### ISSUE THREAD

**Issue by vecerek** [ajv-validator/ajv#1319] opened 2020-11-07 08:43 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Latest version.

**Your typescript code**

```typescript
const validationError: ajv.ValidationError = new ajv.ValidationError([{
    dataPath: ".someKey",
    keyword: "enum",
    params: { allowedValues: ["1", "2", "3"] },
    schemaPath: "",
}]);
validationError.errors[0].params.allowedValues; // TypeError, see below
```

**Typescript compiler error messages**

```
$ tsc --target ES5 --noImplicitAny --noEmit spec/typescript/index.ts
spec/typescript/index.ts:60:34 - error TS2339: Property 'allowedValues' does not exist on type 'ErrorParameters'.
  Property 'allowedValues' does not exist on type 'RefParams'.

60 validationError.errors[0].params.allowedValues;
```

**Describe the change that should be made to address the issue?**
I opened a Draft PR here: https://github.com/ajv-validator/ajv/pull/1318.

**Are you going to resolve the issue?**
I already did, needs review and a bit of help with validating the relationships between keywords and params.

**Comment by epoberezkin** [comment] 2020-11-07 14:46
It's duplicate of https://github.com/ajv-validator/ajv/issues/1090 - implemented in v7-beta

**Closed as completed by epoberezkin** 2020-11-07 14:46 UTC
Labels: typescript

**Comment by Bgshanoams** [comment] 2020-11-08 15:03
Send some coins thiny...
Please help me dear Coder...

На сб, 7.11.2020 г., 16:46 ч. Evgeny Poberezkin <notifications@github.com>
написа:
