### ISSUE TITLE
Schema with discriminator for separated definition of array's items is invalid

### ISSUE THREAD

**Issue by gorshkov-leonid** [ajv-validator/ajv#1908] opened 2022-02-21 14:59 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
8.10.0

Example is here
https://jsfiddle.net/goleon/gvtnL9ao/

**JSON Schema**
```json
{
    "$defs": {
        "A": {
            "properties": {
                "foo": {
                    "const": "x"
                },
                "a": {
                    "type": "string"
                },
            },
            "required": ["a"],
        },
        "B": {
            "properties": {
                "foo": {
                    "enum": ["y", "z"]
                },
                "b": {
                    "type": "string"
                },
            },
            "required": ["b"],

        },
        "C": {
            "type": "object",
            "discriminator": {
                "propertyName": "foo"
            },
            "required": ["foo"],
            "oneOf": [{
                    "$ref": "#/$defs/A"
                }, {
                    "$ref": "#/$defs/B"
                },
            ]
        }
    },
    "type": "object",
    "properties": {
        "cs": {
            "items": {
                "$ref": "#/$defs/C"
            },
            "type": "array"
        }
    },
    "required": [
        "cs"
    ]	

}
```

**Validation result, data AFTER validation, error messages**
ajv7.bundle.js:4842 Uncaught Error: discriminator: oneOf subschemas (or referenced schemas) must have "properties/foo"

But this schema is valid:
```json
{
    "$defs": {
        "A": {
            "properties": {
                "foo": {
                    "const": "x"
                },
                "a": {
                    "type": "string"
                },
            },
            "required": ["a"],
        },
        "B": {
            "properties": {
                "foo": {
                    "enum": ["y", "z"]
                },
                "b": {
                    "type": "string"
                },
            },
            "required": ["b"],

        }
    },
    "type": "object",
    "properties": {
        "cs": {
            "items": {
                "type": "object",
                "discriminator": {
                    "propertyName": "foo"
                },
                "required": ["foo"],
                "oneOf": [{
                        "$ref": "#/$defs/A"
                    }, {
                        "$ref": "#/$defs/B"
                    },
                ]
            },
            "type": "array"
        }
    },
    "required": [
        "cs"
    ]
}
```

**Comment by epoberezkin** [comment] 2022-02-24 07:33
I believe this is a duplicate of #1899 - the fix just got merged

**Closed as completed by epoberezkin** 2022-02-24 07:33 UTC
Labels: duplicate, bug report
