### ISSUE TITLE
Add resolveRefs option or method

### ISSUE THREAD

**Issue by onury** [ajv-validator/ajv#454] opened 2017-04-04 20:47 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

v4.11.5

**Ajv options object (see https://github.com/epoberezkin/ajv#options):**

```javascript
const options = {
    v5: true,
    allErrors: true,
    verbose: false,
    jsonPointers: false,
    uniqueItems: true,
    unicode: true,
    format: 'full',
    formats: {},
    unknownFormats: 'ignore',
    schemas: {},
    missingRefs: true,
    extendRefs: true,
    loadSchema: undefined,
    removeAdditional: false,
    useDefaults: true, 
    coerceTypes: false,
    async: undefined,
    transpile: undefined,
    meta: true,
    validateSchema: true,
    addUsedSchema: true,
    inlineRefs: true,
    passContext: false,
    loopRequired: Infinity,
    ownProperties: false,
    multipleOfPrecision: 0.1,
    errorDataPath: 'object',
    sourceCode: true,
    messages: true,
    beautify: false
}
```

**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
const schema = {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "date": { "$ref": "#/definitions/DateTime" },
        "notes": { "$ref": "#/definitions/String500" }
    },
    "additionalProperties": false,
    "definitions": {
        "DateTime": {
            "type": "string",
            "format": "date-time"
        },
        "String500": {
            "type": "string",
            "maxLength": 500
        }
    }
}
```

**Your code (please use `options`, `schema` and `data` as variables):**

See [RunKit example](https://runkit.com/58e2f649e08ac000145efd81/58e402c144084500137d19c5).
```javascript
var ajv = Ajv(options);
console.log(ajv.compile(schema).schema.properties); 
```
Outputs:
```javascript
{
    "date": { "$ref": "#/definitions/DateTime" }, // still defined as $ref
    "notes": { "$ref": "#/definitions/String500" } // ..
}
```

**What results did you expect?**
I need `$ref` values to be resolved within the compiled schema. But (as noted in docs) `.compile()` method stores the schema as a reference without resolving references. 

`inlineRefs` option seems to be used for inlining referenced schemas but it doesn't. `extendRefs` is something else either.

**Comment by epoberezkin** [comment] 2017-04-04 21:17
duplicate of #22

**Comment by epoberezkin** [comment] 2017-04-04 21:19
$ref is not equivalent to schema inclusion - the expectation you have is wrong.

You can read more on the issue in various discussions in JSON-schema-org, this is the last https://github.com/json-schema-org/json-schema-spec/issues/279#issuecomment-288558322

**Closed as completed by epoberezkin** 2017-04-04 21:19 UTC
Labels: duplicate

**Comment by epoberezkin** [comment] 2017-04-04 21:22
> inlineRefs option seems to be used for inlining referenced schemas but it doesn't.

It affects code generation - with this option `false` $ref is ALWAYS compiled to a function call, by default the code is inlined when possible. The schema itself NEVER changes.

**Comment by epoberezkin** [comment] 2017-04-04 21:25
For a **subset** of possible JSON-schemas $ref can be seen as pre-processing instruction to include the referenced schema in place. In general case such pre-processing is NOT possible. 

Performing any schema manipulation, including inlining $refs in place, is out of scope of this package. The scope of this package is validating data against given schema (specifically, generating code to validate data).

**Comment by onury** [comment] 2017-04-05 03:05
Fair enough. Thanks.

**Comment by epoberezkin** [comment] 2017-04-06 05:52
Added to FAQ: https://github.com/epoberezkin/ajv/blob/master/FAQ.md#generating-schemas-with-resolved-references-ref
