### ISSUE TITLE
new Function() constructor not supported on node 6.10

### ISSUE THREAD

**Issue by gokul-t** [ajv-validator/ajv#673] opened 2018-01-12 15:39 UTC
https://github.com/epoberezkin/ajv/blob/797dfc8c2b0f51aaa405342916cccb5962dd5f21/lib/compile/index.js
line : 118 
new Function() constructor not supported on node version 6.10.

**Comment by epoberezkin** [comment] 2018-01-12 21:18
It works for me in 6.x (including 6.10) in MacOS, it always worked in 6.x on Travis that runs Linux, it also works for users that use Windows. There must be something specific/non-standard in your environment that prevents it from working.

What is the error message you receive?
On what platform do you run Node.js?
Was node.js installed using nvm or in some other way?
Does the issue happen if you install node.js with nvm?
What is the minimal code that allows to reproduce the issue? (e.g. would it happen with `require('ajv')()` - that already invokes Function constructor).

**Comment by gokul-toobler** [comment] 2018-01-15 05:45
1 . What is the error message you receive?

{
  "errorMessage": "Error while loading graphql",
  "errorType": "SyntaxError",
  "stackTrace": [
    "SyntaxError: Unexpected token function",
    "at localCompile (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/ajv/lib/compile/index.js:118:26)",
    "at Ajv.compile (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/ajv/lib/compile/index.js:55:13)",
    "at Ajv._compile (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/ajv/lib/ajv.js:353:27)",
    "at Ajv.compile (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/ajv/lib/ajv.js:113:37)",
    "at Object.<anonymous> (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:612:23)",
    "at __webpack_require__ (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:20:30)",
    "at Object.<anonymous> (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:262:23)",
    "at __webpack_require__ (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:20:30)",
    "at Object.<anonymous> (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:904:14)",
    "at __webpack_require__ (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:20:30)",
    "at Object.defineProperty.value (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:790:18)",
    "at __webpack_require__ (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:20:30)",
    "at Object.defineProperty.value (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:764:15)",
    "at __webpack_require__ (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:20:30)",
    "at Object.defineProperty.value (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:732:14)",
    "at __webpack_require__ (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:20:30)",
    "at Object.<anonymous> (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:655:15)",
    "at __webpack_require__ (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:20:30)",
    "at Object.defineProperty.value (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:63:18)",
    "at Object.<anonymous> (/home/toobler/Projects/boon/boon/backend-boon/backend/.webpack/service/graphql/index.js:66:10)",
    "at Module._compile (module.js:570:32)",
    "at Object.Module._extensions..js (module.js:579:10)",
    "at Module.load (module.js:487:32)",
    "at tryModuleLoad (module.js:446:12)",
    "at Function.Module._load (module.js:438:3)",
    "at Module.require (module.js:497:17)",
    "at require (internal/module.js:20:19)",
    "at Object.createHandler (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/serverless-offline/src/functionHelper.js:35:21)",
    "at handler (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/serverless-offline/src/index.js:499:40)",
    "at Object.internals.handler (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/handler.js:96:36)",
    "at request._protect.run (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/handler.js:30:23)",
    "at internals.Protect.run (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/protect.js:64:5)",
    "at exports.execute (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/handler.js:24:22)",
    "at each (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/request.js:384:16)",
    "at iterate (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/items/lib/index.js:36:13)",
    "at done (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/items/lib/index.js:28:25)",
    "at internals.Auth.payload (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/auth.js:223:16)",
    "at each (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/request.js:384:16)",
    "at iterate (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/items/lib/index.js:36:13)",
    "at done (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/items/lib/index.js:28:25)",
    "at onParsed (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/route.js:402:20)",
    "at Subtext.parse (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/hapi/lib/route.js:423:20)",
    "at next (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/subtext/lib/index.js:45:26)",
    "at Wreck.read (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/subtext/lib/index.js:242:16)",
    "at finish (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/subtext/node_modules/wreck/lib/index.js:374:20)",
    "at wrapped (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/subtext/node_modules/hoek/lib/index.js:875:20)",
    "at onReaderFinish (/home/toobler/Projects/boon/boon/backend-boon/backend/node_modules/subtext/node_modules/wreck/lib/index.js:449:16)",
    "at g (events.js:292:16)",
    "at emitNone (events.js:91:20)",
    "at emit (events.js:185:7)",
    "at finishMaybe (_stream_writable.js:512:14)",
    "at endWritable (_stream_writable.js:522:3)",
    "at Writable.end (_stream_writable.js:487:5)",
    "at IncomingMessage.onend (_stream_readable.js:511:10)",
    "at IncomingMessage.g (events.js:292:16)",
    "at emitNone (events.js:91:20)",
    "at IncomingMessage.emit (events.js:185:7)",
    "at endReadableNT (_stream_readable.js:974:12)",
    "at _combinedTickCallback (internal/process/next_tick.js:80:11)"
  ],
  "offlineInfo": "If you believe this is an issue with the plugin please submit it, thanks. https://github.com/dherault/serverless-offline/issues"
}

2. On what platform do you run Node.js?

ubuntu 14.04

Was node.js installed using nvm or in some other way?

node installed using nvm. 

Does the issue happen if you install node.js with nvm?

yes

What is the minimal code that allows to reproduce the issue? (e.g. would it happen with require('ajv')() - that already invokes Function constructor).

import Ajv from "ajv";
const ajv = new Ajv();
ajv.compile(schema);

**Comment by gokul-toobler** [comment] 2018-01-15 05:57
By function constructor , i mean this thing.

ajv/lib/compile/index.js , line 118
var makeValidate = new Function(
        'self',
        'RULES',
        'formats',
        'root',
        'refVal',
        'defaults',
        'customRules',
        'equal',
        'ucs2length',
        'ValidationError',
        sourceCode
      );

**Comment by epoberezkin** [comment] 2018-01-15 07:39
> Unexpected token function

It most likely refers to async functions not supported in node 6. Do you use async schema?

```
import Ajv from "ajv";
const ajv = new Ajv();
ajv.compile(schema);
```

If it works without the last line, it has nothing to do with function constructor support, as I wrote it can be that your schema is async.

I am closing the issue, if you can't solve please re-submit with ALL info from the template.

**Closed as completed by epoberezkin** 2018-01-15 07:39 UTC

**Comment by gokul-toobler** [comment] 2018-01-15 09:48
import Ajv from "ajv";
import userModel from "../model";

var ajv = Ajv({allErrors: true});

ajv.addKeyword("isEmailAlreadyExists", {
    async: true,
    type: "string",
    validate: isEmailAlreadyExists
});

const schema = {
    "$async": true,
    "type": "object",
    "properties": {
        "displayName": {
            "type": "string"
        },
        "email": {
            "type": "string",
            "format" : "email",
            "isEmailAlreadyExists": {
                "collection": "users"
            }
        },
        "password": {
            "type": "string"
        },
        "status": {
            "type": "boolean"
        }
    },
    "required": ["displayName", "email", "password", "status"]
};

async function isEmailAlreadyExists(meta, data) {
    return !userModel.count({
        email: data
    });
}

export default ajv.compile(schema);

**Comment by gokul-toobler** [comment] 2018-01-15 10:00
yes , it fixed with ajv-async.
require("ajv-async")(ajv);
