### ISSUE TITLE
Coercing individual properties

### ISSUE THREAD

**Issue by scothis** [ajv-validator/ajv#399] opened 2017-01-24 00:23 UTC
**JSON Schema (please make it as small as possible to reproduce the issue):**

```json
{ "type": "string", "coerce": { "type": "number", "minimum": 0, "maximum": 100 } }
```

**Data (please make it as small as possible to reproduce the issue):**

```json
"101"
```

**What results did you expect?**

This schema is attempting to validate that a string is within the range from 0 to 100, after it is converted to a number. In this case, because the numeric value of the string is greater than 100, it should create an error.

The `coerceTypes` config property will cause other errors in my schema (not shown in the example) where it should not automatically coerce the type. I need the ability to coerce individual properties in a schema from strings to numbers, without enabling global coercion. 

I looked at the `addKeyword` docs, but it wasn't immediately clear how to change a value and then validate that value as if it was a different type. I can continue to work on this problem if a little guidance is provided.

**Comment by epoberezkin** [comment] 2017-01-24 09:56
Duplicate of #141 (there is a working implementation of keywords modifying the data). Also please read the [docs](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md) about creating custom keywords (it explains how to modify data too among other things) and see examples of custom keywords in [ajv-keywords](https://github.com/epoberezkin/ajv-keywords), particularly dynamicDefaults (it modifies the data).

**Closed as completed by epoberezkin** 2017-01-24 09:56 UTC
Labels: duplicate

**Comment by scothis** [comment] 2017-01-27 01:28
Thanks @epoberezkin, reading the docs were more clear after a good nights sleep.

For the record, this is what I created:

```js
/**
 * Coerce a string to another data type and validate as if it was that type
 *
 * Useful for numeric values that are transmitted as strings. Since HTTP is
 * text based, all params, query and header properties are strings.
 *
 * Example:
 *   {
 *     "type": "string",
 *     "coerce": {
 *       "type": "number",
 *       "minimum": 0,
 *       "maximum": 22
 *     }
 *   }
 */
validator.addKeyword('coerce', {
  type: 'string',
  compile: function (schema) {
    var validateCoerced = validator.compile(schema);
    return function (data) {
      if (schema.type === 'number' || schema.type === 'integer') {
        data = parseFloat(data);
      } else {
        throw new Error(`Unable to coerce 'string' to '${schema.type}'`);
      }
      return validateCoerced(data);
    };
  }
});
```
