### ISSUE TITLE
Validating multipart/formData type file

### ISSUE THREAD

**Issue by ngingihy** [ajv-validator/ajv#1555] opened 2021-04-20 13:32 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.11.0, yes

**Your typescript code**

I'm trying to use AJV to validate a multipart/formData that has a file in one of its properties. This is the formData Body (Below)
```typescript

{
  title: 'check formData parameters',
  schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: {
    file: { type: 'file' },
    size: { type: 'string', minLength: 1 },
    isExpired: { type: 'boolean' },
    description: { type: 'string', minLength: 1 }
  },
  required: [ 'size', 'isExpired', 'description' ],
  additionalProperties: true
}
```

**Typescript compiler error messages**

```
fileis invalid: data.properties['file'].type should be equal to one of the allowed values, data.properties['file'].type should be array, data.properties['file'].type should match some schema in anyOf
```

**Describe the change that should be made to address the issue?**
Address validating files with ajv

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment] 2021-04-24 08:32
duplicate of #1556

**Closed as completed by epoberezkin** 2021-04-24 08:32 UTC
Labels: typescript
