### ISSUE TITLE
AJV taking too long for compile schema

### ISSUE THREAD

**Issue by pedro-darde** [ajv-validator/ajv#1635] opened 2021-06-02 13:12 UTC
Hi, i am using ajv for validate huge jsons.

I'm parsing 1000 lines to json and sending to ajv.compile but is taking about 30,40 secons to compile, it is normal take too long?

I used to had this working fine, but since last weekend the compile is almost impossible to use.
I'll post my method of validation , if it is something wrong please tell me, i dont know what to do anymore.
`export function validateSchema(
  arrayJson: Array<iSchema>,
  schema: any,
  file: Files,
  maxErrors: number,
  numErrors: number,
  callback: Function
) {
  Arrayerror = [];
  let teste = 0;
  try {
    for (var values of arrayJson) {
      if (numErrors >= maxErrors) {
        break;
      }
      const ajvTeste = new Ajv({
        strict: false,
        allErrors: true,
      });
      require("ajv-keywords")(ajvTeste);
      addFormats(ajvTeste);
      AjvErrors(ajvTeste);

      let validate2 = ajvTeste.compile(schema);

      if (validate2(values)) {
        teste++;
      } else {
        ErrorFields =
          validate2.errors &&
          validate2.errors?.map((vals) => {
            return vals.dataPath;
          });
      }

      if (ajvTeste.errorsText(validate2.errors) !== "No errors") {
        numErrors++;
        Arrayerror.push({
          line: values.seq,
          errors: ajvTeste.errorsText(validate2.errors).split(","),
          campo: Array.prototype.join.call(ErrorFields).split(","),
          file: file,
          layout: values.tabela,
          full_line_error: values.linha,
        });
      }
    }
    return callback(Arrayerror, numErrors);
  } catch (e) {
    console.log("w");
  }
}`

**Comment by epoberezkin** [comment] 2021-06-06 14:16
Difficult to say without actual complete example, but it might be a duplicate of #1581

**Comment by pedro-darde** [comment] 2021-06-08 11:47
It doesnt throw an error, just take too long to validate 10000 lines
10000 lines form me it's like 10000 json's, take more than a minute
My code below

```
import Ajv from "ajv";
import Files from "../models/Files";

const AjvErrors = require("ajv-errors");
import addFormats from "ajv-formats";
export var boolmaxErrors: boolean;
var ErrorFields: string[] | null | undefined;
interface iArrayError {
  line: number;
  errors: string[];
  campo: string[];
  file: Files;
  layout: string;
  full_line_error: string;
}

interface iSchema {
  tabela: string;
  linha: string;
  seq: number;
}
let Arrayerror: Array<iArrayError> = [];
export function validateSchema(
  arrayJson: Array<iSchema>,
  schema: any,
  file: Files,
  maxErrors: number,
  numErrors: number,
  callback: Function
) {
  Arrayerror = [];
  try {
    for (var values of arrayJson) {
      if (numErrors >= maxErrors) {
        break;
      }
      const ajvTeste = new Ajv({
        strict: false,
        allErrors: true,
        next: false,
      });
      require("ajv-keywords")(ajvTeste);
      addFormats(ajvTeste);
      AjvErrors(ajvTeste);

      let validate2 = ajvTeste.compile(schema);

      if (!validate2(values)) {
        ErrorFields =
          validate2.errors &&
          validate2.errors?.map((vals) => {
            return vals.dataPath;
          });
      }

      if (ajvTeste.errorsText(validate2.errors) !== "No errors") {
        numErrors++;

        Arrayerror.push({
          line: values.seq,
          errors: ajvTeste.errorsText(validate2.errors).split(","),
          campo: Array.prototype.join.call(ErrorFields).split(","),
          file: file,
          layout: values.tabela,
          full_line_error: values.linha,
        });
      }
    }
    return callback(Arrayerror, numErrors);
  } catch (e) {
    console.log("w");
  }
}
```

**Comment by epoberezkin** [comment] 2021-06-08 11:58
Looking at your code you both instantiate Ajv and compile schema in the loop. If this arrayJson is large (it's not part of the example, so I cannot really execute it) then it can be slow indeed.

You have to instantiate ajv and compile your schemas once per application lifetime, not for every validation, and definitely not for every item in the array. 

See https://ajv.js.org/guide/managing-schemas.html

**Closed as completed by epoberezkin** 2021-06-08 11:58 UTC
Labels: usage

**Comment by pedro-darde** [comment] 2021-06-08 12:14
For shure, thanks for help, it really helped me in this case
:)

**Comment by epoberezkin** [comment] 2021-06-08 20:52
Great!

**Comment by kalanamt** [comment] 2022-01-13 22:13
> Looking at your code you both instantiate Ajv and compile schema in the loop. If this arrayJson is large (it's not part of the example, so I cannot really execute it) then it can be slow indeed.
> 
> You have to instantiate ajv and compile your schemas once per application lifetime, not for every validation, and definitely not for every item in the array.
> 
> See https://ajv.js.org/guide/managing-schemas.html

`You have to instantiate ajv and compile your schemas once per application lifetime,`  Would like to know the steps to perform this

**Comment by epoberezkin** [comment] 2022-01-15 08:18
This depends on which frameworks you use and how your application is structured, Ajv doesn't prescribe any specific steps other than API it exposes.

There are some recipes here: https://ajv.js.org/guide/managing-schemas.html
