### ISSUE TITLE
applyDefault option

### ISSUE THREAD

**Issue by Duncan00** [ajv-validator/ajv#75] opened 2015-11-23 05:55 UTC
Does ajv have an option to apply default value from schema to input json if the property is not exist?
It would be nice to have feature.

**Comment by epoberezkin** [comment] 2015-11-23 06:53
Duplicate of #42. Not yet, but it's in the plan :)

**Comment by Duncan00** [comment] 2015-11-23 09:32
Thanks~ i just use https://www.npmjs.com/package/json-schema-defaults before doing validation now.

var defaults = require('json-schema-defaults');
var default_json = defaults(validate.schema); // <~ cannot set default value to $ref properties
_.defaultsDeep(payload, default_json);

**Comment by epoberezkin** [comment] 2015-11-23 10:48
Ah, interesting, thanks. I will look at this package... I though to do it after async validation but I will do it before. Without catering for edge-cases that are not that important it's pretty easy actually. And it will be much faster, as it will be compiled into the validating function.

Closing this one now, feel free to post to #42 if you have any questions

**Closed as completed by epoberezkin** 2015-11-23 10:48 UTC
Labels: duplicate
