### ISSUE TITLE
if then validation failing if property is not present

### ISSUE THREAD

**Issue by capitnflam** [ajv-validator/ajv#753] opened 2018-04-06 09:40 UTC
If the property used in the if clause is not present in the validated data then the validation fails with an error about the then clause not being matched.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

Using version 6.4.0

**Ajv options object**

```json
{
  allErrors: true
}
```

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "foo": { "type": "string" },
    "bar": { "type": "string" }
  },
  "if": {
    "properties": {
      "foo": { "enum": ["bar"] }
    }
  },
  "then": { "required": ["bar"] }
}
```

**Sample data**

```json
{}
```

**Your code**

```javascript
var Ajv = require('ajv');
var ajv = new Ajv(options);

var validate = ajv.compile(schema);
var valid = validate(data);
if (valid)
  console.log('Valid!');
else
  console.log('Invalid: ' + ajv.errorsText(validate.errors));
```

**Validation result, data AFTER validation, error messages**

```
Invalid: data should have required property 'bar', data should match "then" schema
```

**What results did you expect?**
As the `foo` property is not present, I would expect the if clause to not match and thus having the following output: 
```
Valid!
```

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment] 2018-04-06 13:34
duplicate of https://github.com/epoberezkin/ajv/issues/724
also see https://github.com/epoberezkin/ajv/blob/master/FAQ.md#using-json-schema

**Closed as completed by epoberezkin** 2018-04-06 13:34 UTC
Labels: duplicate, OK
