### ISSUE TITLE
Module '"../node_modules/ajv/lib/ajv"' has no exported member 'DefinedError'.ts(2305)

### ISSUE THREAD

**Issue by abhay1432** [ajv-validator/ajv#1411] opened 2021-01-27 04:49 UTC
**The version of Ajv you are using**

**Operating system and node.js version**

**Package manager and its version**

**Link to (or contents of) package.json**

"dependencies": {
          ...    
         "ajv": "^6.12.6",
         ...
         }
     
**Error messages**
Module '"../node_modules/ajv/lib/ajv"' has no exported member 'JSONSchemaType'.
Module '"../node_modules/ajv/lib/ajv"' has no exported member 'DefinedError'.ts(2305)

**The output of `npm ls`**
| +-- @angular-devkit/core@10.1.7
| | +-- ajv@6.12.4
| | | +-- fast-deep-equal@3.1.3 deduped
| | | +-- fast-json-stable-stringify@2.1.0 deduped
| | | +-- json-schema-traverse@0.4.1
| | | `-- uri-js@4.4.1 deduped
| | +-- fast-json-stable-stringify@2.1.0 deduped

**Comment by abhay1432** [comment] 2021-01-27 04:51
I recently installed the ajv  and I seeing an issue with the following line of code 
import Ajv, {JSONSchemaType, DefinedError} from "ajv"

this is throwing me the above error,. Any help on how I can resolve this issue? I have tried deleting node_modules and then tried installing them, but I am still facing the same issue.

**Comment by epoberezkin** [comment] 2021-01-27 16:06
This looks like conflict with multiple installed Ajv versions - they are exported in 7.0.3 but either your code or some dependencies are confused with which version they are using - not clear from the issue. Please try re-installing everything and post the full case to reproduce the issue if it persists.

**Comment by epoberezkin** [comment] 2021-01-27 16:15
going to close it for now.

**Closed as completed by epoberezkin** 2021-01-27 16:15 UTC
Labels: installation

**Comment by RobertZetterlund** [comment] 2021-04-23 12:12
Hi, I had a similar issue but with `JSONSchemaType` only. It turns out version was incorrect. On fresh install i recieved 6.12.x but upgrading the package resolved my issue:

`npm install ajv@latest`
