### ISSUE TITLE
Removing a schema doesn't remove the schema and can still validate against it from the instance

### ISSUE THREAD

**Issue by sahilda** [ajv-validator/ajv#1630] opened 2021-05-28 19:44 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
Yes, using latest, v8.5.0

**Ajv options object**

```javascript
{ code: { optimize: false } }
```

**JSON Schema**

Please see the code section - this is not about a specific schema or data, but about how the ajv instance is retaining a copy of "removed" schemas.

**Sample data**

Please see the code section - this is not about a specific schema or data, but about how the ajv instance is retaining a copy of "removed" schemas.

**Your code**

Here's a codesandbox link with the issue: 
https://codesandbox.io/s/ajv-playground-forked-qlry4?file=/src/index.js:44-73

```javascript
import Ajv from "ajv";

const ajv = new Ajv({ code: { optimize: false } });

ajv.addSchema(
  { type: "object", properties: { field0: { type: "number" } } },
  "schema"
);
console.log(ajv.getSchema("schema").schema);
console.log(ajv.validate("schema#/properties/field0", 3));
console.log(ajv.validate("schema#/properties/field0", "abc"));
// you cannot add the same key twice!
// ajv.addSchema({ type: "object", properties: { field0: { type: "number" } } }, "schema");

ajv.removeSchema("schema");
ajv.addSchema(
  { type: "object", properties: { field1: { type: "string" } } },
  "schema"
);
console.log(ajv.getSchema("schema").schema);
console.log(ajv.validate("schema#/properties/field0", 3));
console.log(ajv.validate("schema#/properties/field0", "abc"));
console.log(ajv.validate("schema#/properties/field1", 3));
console.log(ajv.validate("schema#/properties/field1", "abc"));

```

**Validation result, data AFTER validation, error messages**

```

{type: "object", properties: Object}
true
false
{type: "object", properties: Object}
true
false
false
true
```

**What results did you expect?**

After removing the first schema, a call to `ajv.validate("schema#/properties/field0", 3)` would throw an error.

**Are you going to resolve the issue?**

I would first like to confirm that this is an issue, and is not by design. If so, I might be interested.

**Comment by epoberezkin** [comment] 2021-05-29 07:00
duplicate of #1293

**Closed as completed by epoberezkin** 2021-05-29 07:00 UTC
Labels: duplicate, limitation
