### ISSUE TITLE
ajv validate always return true

### ISSUE THREAD

**Issue by moonformeli** [ajv-validator/ajv#1103] opened 2019-10-16 20:31 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
```
ajv: 6.10.2
typescript-json-schema: 0.40.0
```

**Ajv options object**

```javascript


```

**JSON Schema**

```json
// ISoccerPayloadSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ISport": {
      "type": "object",
      "properties": {
        "propA": {
          "type": "number"
        }
      },
      "required": [
        "propA"
      ]
    }
  }
}
```

**Sample data**

```ts
interface ISport {
  propA: number;
}
```

**Your code**

```ts
import * as AJV from "ajv";
import * as json from "../node/schema/ISoccerPayloadSchema.json";

describe("JSON Schema", () => {
  it("ajv test", () => {
    // Arrange
    const ajv = new AJV();
    const validate = ajv.compile(json);

    // Act
    const validString = validate({ propA: "h" });
    const validNumber = validate({ propA: 1 });
    const validBoolean = validate({ propA: false });
    const validObject = validate({ propA: { msg: "hello world" } });
    const validNull = validate(null);
    const validUndefined = validate(undefined);

    // Assert
    expect(validString).toBe(true);
    expect(validNumber).toBe(true);
    expect(validBoolean).toBe(true);
    expect(validObject).toBe(true);
    expect(validNull).toBe(true);
    expect(validUndefined).toBe(true);
  });
});
```

**Validation result, data AFTER validation, error messages**

```


```

**What results did you expect?**
I wanted my code to work properly. But all `expect` are true in that code. What's I'm missing?

**Are you going to resolve the issue?**

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-10-17 00:23
definitions not properties.

**Comment by moonformeli** [comment] 2019-10-17 04:47
> definitions not properties.

Can you explain it more detaily, please?

**Comment by epoberezkin** [comment] 2019-10-17 10:39
I suspect it's a duplicate of https://github.com/epoberezkin/ajv/issues/1101

**Comment by epoberezkin** [comment] 2019-10-17 10:40
the workaround is to use require: https://github.com/epoberezkin/ajv/issues/1101#issuecomment-541704883

**Closed as completed by epoberezkin** 2019-10-17 10:40 UTC
Labels: duplicate, compatibility, typescript
