### ISSUE TITLE
option compile from addKeyword doesn't change on a remove and then add again

### ISSUE THREAD

**Issue by rgpro007** [ajv-validator/ajv#2411] opened 2024-04-08 15:36 UTC
Here my issue (if it's one):

I setup a keyword with addKeyword and the compile option. I have some external variables used inside. At the first iteration everything is ok, but at the second one we see the variables doesn't change. Is it a normal behavior or an issue ?

**What version of Ajv are you using?**

version 8.12.0

**Your code**

```javascript
const AjvModule = require('ajv');
const ajv = new AjvModule();

const keyword = "variableKeywork";
const schema = {
    "description": "test",
    "type": "object",
    "properties": {
        "item1": {
            "type": "string"
        }
    },
    "variableKeywork": true
};

test({
    item1: "test"
}, true);
console.log('-------------------------');

setTimeout(() => {
    test({
        item1: 1
    }, false);
}, 5000);

function test(desc, value) {
    const now = new Date();
    const time = now.getTime();
    console.log(`Current time: ${time}`);
    ajv.addKeyword({
        keyword: keyword,
        modifying: true,
        compile: (value) => function validate(data, root) {
            console.log(`Time inside addKeyword: ${time} and value = ${value}`);
            return true
        }
    });
    console.log(`keyword present : ${JSON.stringify(ajv.getKeyword(keyword))}`);
    const validate = ajv.compile(schema);
    const isDataValid = validate(desc);
    ajv.removeKeyword(keyword);
    console.log(`data valid: ${isDataValid}`)
    console.log(`keyword present: ${JSON.stringify(ajv.getKeyword(keyword))}`);
}
```

**Output obtained**

```
Current time: 1716967536094
keyword present : {"keyword":"variableKeywork","modifying":true,"type":[],"schemaType":[]}
Time inside addKeyword: 1716967536094 and value = true
data valid: true
keyword present: false
-------------------------
Current time: 1716967541145
keyword present : {"keyword":"variableKeywork","modifying":true,"type":[],"schemaType":[]}
Time inside addKeyword: 1716967536094 and value = true
data valid: false
keyword present: false
```

**What results did you expect?**

the ajv.removeKeyword really remove the keyword and allow us the define it again.

**Are you going to resolve the issue?**

**Comment by jasoniangreen** [comment] 2024-05-14 22:43
Can you please produce a minimal example using this [runkit template](https://runkit.com/esp/ajv-issue)? It should be possible to reproduce the issue without `express`.

**Comment by rgpro007** [comment] 2024-05-29 07:34
Hello,
I have updated the example with a runkit template : [runkit example](https://runkit.com/rgpro007/ajv-addkeyword-issue)

**Comment by jasoniangreen** [comment] 2024-06-07 21:22
I have looked into this and I have been able to replicate with an even simpler example.
https://runkit.com/jasoniangreen/addkeyword-bug-2411

**Comment by jasoniangreen** [comment] 2024-06-08 13:59
I got to the bottom of the issue @rgpro007. Here you can see [my minimal example](https://runkit.com/jasoniangreen/addkeyword-bug-2411) that reproduces the issue and then fixes it. The reason you are hitting this issue is that for performance reasons, AJV caches a lot of things. In this case you have a cached schema which has already been compiled. When you try to compile the same schema again, it skips certain steps to save time.

The simple solution is to use `ajv.removeSchema` (see line 21) before you try and compile it again. Alternatively you could clone the schema `{...schema}` which would also work because the cache uses a WeakMap which recognises the schema by reference.

**Comment by jasoniangreen** [comment] 2024-06-08 14:04
After reviewing the docs I am confident this is how it is intended to be and the docs are clear enough on how you should only compile schemas once. So I will close this one and leave you with two links:
- https://ajv.js.org/guide/managing-schemas.html#cache-key-schema-vs-key-vs-id
- https://ajv.js.org/guide/managing-schemas.html#caching-schemas-in-your-code

**Closed as completed by jasoniangreen** 2024-06-08 14:04 UTC
Labels: question

**Comment by rgpro007** [comment] 2024-06-10 08:56
Thank for you help.
I will modify my code.
