### ISSUE TITLE
Encoded definition names pass full schema validation but throws during validation

### ISSUE THREAD

**Issue by thejuan** [ajv-validator/ajv#1134] opened 2019-12-12 01:01 UTC
We encode definition names as well as the uri component in $ref as AWS requires it.
The schema passes full validation in AJV, but throws missing ref error when attempt to use it to validate. It expects the definition names to be unencoded.

Ideally the below schema would work during validation, but if not supported validateSchema should throw.

**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.10.2

**Ajv options object**

`var ajv = new Ajv({allErrors: true, format: 'full'});`

**JSON Schema**

```json
var schema = {

    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Base%3Cboolean%3E": {
            "additionalProperties": false,
            "properties": {
                "a": {
                    "type": "boolean"
                }
            },
            "required": [
                "a"
            ],
            "type": "object"
        },
        },
        "properties":{
          "test": {"$ref": "#/definitions/Base%3Cboolean%3E"}
        }
}
;

```

https://runkit.com/thejuan/ajv-1131

**Comment by epoberezkin** [comment] 2019-12-14 16:25
isn't it duplicate of #1131 ?

**Comment by epoberezkin** [comment] 2019-12-14 16:28
It is a bit different situation, but the behaviour is correct.

It is allowed to use encoded URIs in $refs, but the referenced properties in the schema should not be encoded.

So it would work in this way:

https://runkit.com/esp/5df50d116a1cb5001a049e47

**Closed as completed by epoberezkin** 2019-12-14 16:28 UTC
Labels: usage

**Comment by thejuan** [comment] 2019-12-14 21:23
The bug is that validateSchema should fail but it doesn’t.

**Comment by epoberezkin** [comment] 2019-12-15 08:36
Why should it fail? It’s a valid URI.

**Comment by epoberezkin** [comment] 2019-12-15 08:38
There are three stages: schema validation, schema compilation, data validation.

In this case, the schema is valid - so it passes. Because URI is not in the schema - it fails compilation.

**Comment by thejuan** [comment] 2019-12-15 21:54
Fair enough, I had assumed validating the schema would ensure it was usable, but validating it only matches the schema makes sense. An option to validate reference resolution would be nice, but can do externally or just run a dummy data validation and look for MissingRef errors

**Comment by epoberezkin** [comment] 2019-12-15 22:20
You need to compile it with ajv.compile, it returns function that can be used for validation
