### ISSUE TITLE
default object creation

### ISSUE THREAD

**Issue by cemtopkaya** [ajv-validator/ajv#57] opened 2015-10-05 19:27 UTC
It would be perfect if ajv can create default object from the schema. Is there any way to put this feature on this lovely, fastest almost perfect ;) beauty?

**Comment by epoberezkin** [comment] 2015-10-06 05:45
duplicate of #42. Or did you mean something else?

**Comment by epoberezkin** [comment] 2015-10-15 18:10
@cemtopkaya closing as duplicate, please reopen if you meant something else. Thank you

**Closed as completed by epoberezkin** 2015-10-15 18:10 UTC
Labels: duplicate, thinking
