### ISSUE TITLE
[Request] selective validation

### ISSUE THREAD

**Issue by braco** [ajv-validator/ajv#272] opened 2016-08-12 18:15 UTC
Pardon if this has been addressed. There's a broad use case here that I don't think ajv covers:

Let's say you have a schema defined for a large user input form.

The user completes the form one section at a time. Each section is validated before he's allowed to move on.

How do you validate each section without either:
1. creating separate schemas (which runs afoul of SoC, ties the UI to the schema, complicates validation with `$ref` + `required`)
2. validating the entire form every time there's a change (which will hit sections not encountered yet and is unnecessary)

What if we could just check a list of fields?
`validate(data, { fields: ['foo', 'bar'] })`

This would keep `required: [...]` directives in place for the larger and immediate scope, maintain one central source of truth for the validator,  and would  be another point in favor of speed, if nothing else.

Each field would selectively run the validator on itself, and it would always be in the context of the parent schema.

**Comment by epoberezkin** [comment] 2016-08-13 06:20
Thank you for the issue. It is essentially a duplicate of #211.

The best approach I think is to have each form section as a separate definition with ID in the schema, then you can refer to them from the outside:

``` javascript
ajv.validate({$ref: 'schema.json#section1'}, data);
```

**Comment by braco** [comment] 2016-08-13 17:17
Thanks @epoberezkin, missed that.

Isn't that a pretty big loss of separation of concerns? The schema itself is business logic, whereas the UI is merely circumstantial, and will be different across various platforms.

Additionally, the schema needs to define what elements are required for the eventual payload. Is that even possible with $ref? Each section would essentially be a ref plus a slice of the `required` array from the parent schema. One field $ref may be required in one section and not in another. 

I guess the alternative could be a slice function that chopped up the parental schema and compiled an instance for every section...?

**Comment by epoberezkin** [comment] 2016-08-13 18:10
Yes, this approach has limitations.
In cases the UI structure is different from data structure you need to have some other ways to generate schemas from parent schema. You could use a custom keyword to mark up sections and use some function or processing schema to extract smaller schemas.

**Closed as completed** 2016-08-13 18:39 UTC
Labels: duplicate, usage

**Comment by StefJoynson** [comment] 2018-05-25 11:44
You can just do adj.validate(schema.properties.item, thingToValidate).

**Comment by ashnur** [comment] 2018-06-21 14:57
@StefJoynson that is quite ugly. Ideally I would like to use the same JSON pointers for my data and for the schema that describes the data and against which the data is validated. Now, based on your answer, I would have to manipulate my json pointers for each schema...
