### ISSUE TITLE
Default values inside referenced schemas will not fill default on validation

### ISSUE THREAD

**Issue by filipesilva** [ajv-validator/ajv#688] opened 2018-01-26 20:56 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`6.1.0`

**Ajv options object**

```javascript
{ useDefaults: true }
```

**JSON Schema**

```json
var schema = {
  "$async": true,
  "$id": "http://example.com/schemas/schema.json",
  "type": "object",
  "properties": {
    "foo": { "$ref": "defs.json#/definitions/defaultStr" },
    "bar": { "$ref": "defs.json#/definitions/str" },
    "baz": { "type": "string", "default": "baz" }
  }
};

var defsSchema = {
  "$id": "http://example.com/schemas/defs.json",
  "definitions": {
    "defaultStr": { "type": "string", "default": "foo" },
    "str": { "type": "string" }
  }
};
```

**Sample data**

```json
{"bar": "bar"}
```

**Your code**

I also have a runkit here: https://runkit.com/filipesilva/5a6b8e108f3ceb0012877755

```javascript
const Ajv = require("ajv");

var schema = {
  "$async": true,
  "$id": "http://example.com/schemas/schema.json",
  "type": "object",
  "properties": {
    "foo": { "$ref": "defs.json#/definitions/defaultStr" },
    "bar": { "$ref": "defs.json#/definitions/str" },
    "baz": { "type": "string", "default": "baz" }
  }
};

var defsSchema = {
  "$id": "http://example.com/schemas/defs.json",
  "definitions": {
    "defaultStr": { "type": "string", "default": "foo" },
    "str": { "type": "string" }
  }
};

var ajv = new Ajv({ useDefaults: true });
ajv.addSchema(defsSchema);
var validate = ajv.compile(schema);
test({bar: 'bar'})

function test(data) {
    return validate(data)
    .then(() => console.log('valid data: ' + JSON.stringify(data)))
    .catch((err) => {
        if (err instanceof Ajv.ValidationError)
            console.log('invalid data: ' + JSON.stringify(data), 'errors:', err.errors);
        else console.log(err);
    });
}
```

**Validation result, data AFTER validation, error messages**

```
{"bar":"bar","baz":"baz"}
```

**What results did you expect?**
I expected the default for `foo`, specified in `defs.json`, to be filled in like `baz` was.
```
{"foo": "foo","bar":"bar","baz":"baz"}
```

**Are you going to resolve the issue?**
I am not sure if this is a bug or intended behaviour.

In https://github.com/epoberezkin/ajv#assigning-defaults the following caveat is listed:
> default keywords in other cases are ignored: ... in schemas generated by custom macro keywords

But I don't really know if using `$ref` falls within that category.

**Comment by filipesilva** [comment] 2018-01-26 21:17
This seems similar to defaults also not working with merge (https://runkit.com/filipesilva/5a6b98558f3ceb0012877ec2), but that is reported in https://github.com/epoberezkin/ajv-merge-patch/issues/16 and is marked as a future enhancement.

**Comment by filipesilva** [comment] 2018-01-26 21:23
I was trying `$ref` within the same document and it seems that doesn't fill in defaults as well: https://runkit.com/filipesilva/5a6b9bbd42f34400128620eb

**Comment by epoberezkin** [comment] 2018-01-29 13:03
duplicate of https://github.com/epoberezkin/ajv/issues/337

**Closed as completed by epoberezkin** 2018-01-29 13:03 UTC
Labels: duplicate

**Comment by filipesilva** [comment] 2018-01-29 13:32
Aw jeez, I didn't see that one. Thanks for directing me to the right issue!

**Comment by epoberezkin** [comment] 2018-01-29 13:32
no problem at all
