### ISSUE TITLE
removeAdditional & allErrors causing odd validation results

### ISSUE THREAD

**Issue by nurdism** [ajv-validator/ajv#1495] opened 2021-03-16 09:46 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
7.2.1 (reproducible in 8.0.0-beta.1)

**Ajv options object**

```javascript
{
  removeAdditional: true,
  allErrors: true,
}
```

**JSON Schema**

```json
{
  "oneOf": [
    {
      "type": "object",
      "required": ["type", "a"],
      "properties": {
        "type": { "type": "string", "const": "a" },
        "a": { "type": "string" },
      },
      "additionalProperties": false,
    },
    {
      "type": "object",
      "required": ["type", "b"],
      "properties": {
        "type": { "type": "string", "const": "b" },
        "b": { "type": "string" },
      },
      "additionalProperties": false,
    },
    {
      "type": "object",
      "required": ["type", "c"],
      "properties": {
        "type": { "type": "string", "const": "c" },
        "c": { "type": "string" },
      },
      "additionalProperties": false,
    }
  ],
}
```

**Sample data**

```json
{ "type": "a", "a": "this is a test" } 
{ "type": "b", "b": "this is a test" }
{ "type": "c", "c": "this is a test" }
```

**Your code**

https://runkit.com/nurdism/60507beb0e9871001aacfc1f

```javascript
var Ajv = require('ajv').default;

ajv = new Ajv({
  removeAdditional: true,
  allErrors: true,
});

var schema = {
  "oneOf": [
    {
      "type": "object",
      "required": ["type", "a"],
      "properties": {
        "type": { "type": "string", "const": "a" },
        "a": { "type": "string" },
      },
      "additionalProperties": false,
    },
    {
      "type": "object",
      "required": ["type", "b"],
      "properties": {
        "type": { "type": "string", "const": "b" },
        "b": { "type": "string" },
      },
      "additionalProperties": false,
    },
    {
      "type": "object",
      "required": ["type", "c"],
      "properties": {
        "type": { "type": "string", "const": "c" },
        "c": { "type": "string" },
      },
      "additionalProperties": false,
    }
  ],
};

var validate = ajv.compile(schema);

var a = { "type": "a", "a": "this is a test" }; // passes with "a" missing property
console.log(validate(a));
console.log(validate.errors);

var b = { "type": "b", "b": "this is a test" }; // fails
console.log(validate(b));
console.log(validate.errors);

var c = { "type": "c", "c": "this is a test" }; // fails
console.log(validate(c));
console.log(validate.errors);
```

**What results did you expect?**
all three object to pass validation untouched

**Are you going to resolve the issue?**
no

**Comment by epoberezkin** [comment] 2021-03-17 07:47
This is not a bug, ajv validates all subschemas in oneOf in order, that's why the first data `a` passes - it is valid against the first subschema - and the others fail - they are modified by the previous subschemas and become invalid.

This is covered in [faq.md](https://ajv.js.org/faq.html#additional-properties-inside-compound-keywords-anyof-oneof-etc) and in docs [here](https://ajv.js.org/guide/modifying-data.html#removing-additional-properties).

JSON Schema standard does not have support for discriminated unions.

There are two options:
- OpenAPI discriminator keyword - extension of JSON Schema - that is just released in ajv v8.0.0-beta.2 (see #1119, also [here](https://github.com/ajv-validator/ajv/blob/v8/docs/json-schema.md#discriminator-))
- [JSON Type Definition](https://ajv.js.org/json-type-definition.html) has discriminator form

**Closed as completed by epoberezkin** 2021-03-17 07:47 UTC
Labels: usage
