### ISSUE TITLE
Problem with serialize option.

### ISSUE THREAD

**Issue by YozhEzhi** [ajv-validator/ajv#880] opened 2018-11-09 14:40 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
6.5.5

**Ajv options object**
```javascript
{allErrors: true, schemaId: 'auto'}
```

**Your code**

```javascript
import * as Ajv from 'ajv';
...
    componentDidMount() {
        this.validator = new Ajv({allErrors: true, schemaId: 'auto'});
    }
...
```

**Validation result, data AFTER validation, error messages**

```
ajv.js:300 Uncaught (in promise) TypeError: serialize is not a function
    at Ajv._addSchema (ajv.js:300)
    at Ajv.addSchema (ajv.js:136)
    at Ajv.addMetaSchema (ajv.js:151)
    at addDraft6MetaSchema (ajv.js:455)
    at new Ajv (ajv.js:73)
    at Page.componentDidMount (Page.tsx:82)
    at CallbackQueue.notifyAll (react.min.js:869)
    at ReactReconcileTransaction.close (react.min.js:12870)
    at ReactReconcileTransaction.closeAll (react.min.js:15699)
    at ReactReconcileTransaction.perform (react.min.js:15646)
```

**What results did you expect?**
Want to able to initiate Ajv instanse.

Second problem:
I tried to use `new Ajv({allErrors: true, serialize: false, schemaId: 'auto'})` .
But Options interface in `ajv/lib/ajv.d.ts` has no 'serialize' field.

**Comment by epoberezkin** [comment] 2018-11-09 20:00
“Serialize” option indeed has to be defined in types, but that not the problem here. The issue seems to be caused by something assigning this property to something other than undefined, maybe on prototype chain, and that leads to Ajv failing to properly initialise it with the required function - you can check the source code. The error says it’s not a function - you need to check what it is and that may give you a clue to what assigns it.

**Comment by epoberezkin** [comment] 2018-11-09 20:02
I am closing the issue here, if you can’t resolve - please resubmit using template for compatibility issues.

**Closed as completed by epoberezkin** 2018-11-09 20:02 UTC
Labels: compatibility

**Comment by YozhEzhi** [comment] 2018-11-10 13:40
This is so weird :)

Code: `new Ajv({allErrors: true, schemaId: 'auto'});`

Constructor:
![1](https://user-images.githubusercontent.com/2706062/48301989-5c3f8a80-e507-11e8-9e64-6dea0260c12b.JPG)

There is webpack-dev-server's `images/index.js` with code:
![2](https://user-images.githubusercontent.com/2706062/48302060-47afc200-e508-11e8-9476-e044a7c5cea6.JPG)

I think that I'm doing something wrong using webpack + ajv.

**Comment by epoberezkin** [comment] 2018-11-10 21:30
no idea what is going on here

**Comment by kfrajtak** [comment] 2021-01-21 08:00
Fixed this issue by installing `fast-json-stable-stringify`. I found it when digging into the code. 

Don't know why it failed, since it has been working fine before.

**Comment by rorywillis-fa** [comment] 2021-01-21 18:09
> Fixed this issue by installing `fast-json-stable-stringify`. I found it when digging into the code.
> 
> Don't know why it failed, since it has been working fine before.

Running into this same issue today. This worked.

**Comment by epoberezkin** [comment] 2021-01-21 22:50
Sorry, is it in v7 or 6.12?

**Comment by kfrajtak** [comment] 2021-01-22 07:49
6.9.1
