### ISSUE TITLE
AJV cant resolve external json file path

### ISSUE THREAD

**Issue by DardanHaliti** [ajv-validator/ajv#1111] opened 2019-10-25 13:23 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
I am using ajv 6.10.2 and i have two json files in the same folder, the error seems to happen that ajv cant resolve the $ref to another json file.

**Ajv options object**
I have tried those references

https://github.com/epoberezkin/ajv/issues/534
https://github.com/epoberezkin/ajv/issues/561

```javascript


```

**JSON Schema**

file 1
```
{
    "$id":"/path/to/file/schema1.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "$ref": "/path/to/file/schema1.json#/schema1",
    "schema1": {
        "title": "",
        "description": "",
        "type": "object",
        "properties": {
            "name": {
                "description": "",
                "type": "string"
            },
            "properties": {
                "description": "",
                "type": "array",
                "items": {
                    "$id": "/path/to/file/schema2.json",
                    "$ref": "/path/to/file/schema2.json#/schema2" //<- if i delete this it works but i need this
                }
            }
        },
        "required": ["name"]
    }
}
```
and file 2
```
{
    "$id":"/path/to/file/schema2.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "$ref": "/path/to/file/schema2.json#/schema1",
    "property": {
        "title": "Title",
        "description": "Some description",
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "some discription"
            }
        },
        "required": ["name"]
    }
}
```

**Sample data**

```json


```

**Your code**

```
const fs = require('fs');
let Ajv = require('ajv');
let ajv = new Ajv({allErrors: true, schemaId: 'auto'});
let file1 = JSON.parse(fs.readFileSync("../path/to/file/schema1.json", 'utf8'));
let file2 = JSON.parse(fs.readFileSync("../path/to/file/schema2.json", 'utf8'));
ajvj.addSchema(file2);
ajvj.addSchema(file1);
console.log(ajv.validate(file1, {}), ajv.errors);
//console.log(ajv.validate({}), ajv.errors); // it always returns true
```

**Validation result, data AFTER validation, error messages**

```
Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at _normalizeComponentEncoding (/app/node_modules/uri-js/dist/es5/uri.all.js:790:82)
    at Object.parse (/app/node_modules/uri-js/dist/es5/uri.all.js:936:13)
    at getFullPath (/app/node_modules/ajv/lib/compile/resolve.js:209:15)
    at Ajv.resolveSchema (/app/node_modules/ajv/lib/compile/resolve.js:72:16)
    at Ajv.resolveRecursive (/app/node_modules/ajv/lib/compile/resolve.js:102:27)
    at Ajv.resolveSchema (/app/node_modules/ajv/lib/compile/resolve.js:77:31)
    at Ajv.getJsonPointer (/app/node_modules/ajv/lib/compile/resolve.js:134:35)
    at Ajv.resolveSchema (/app/node_modules/ajv/lib/compile/resolve.js:95:25)
    at Ajv.resolveRecursive (/app/node_modules/ajv/lib/compile/resolve.js:102:27)
/app/node_modules/ajv/lib/ajv.js:350
    throw e;
    ^
```

**What results did you expect?**
I expect true or false, if the json object is correct(true) if it is empty(false)

**Are you going to resolve the issue?**
I am trying to...

**Comment by epoberezkin** [comment] 2019-10-25 18:59
Suggestions to help investigating:

- Reduce code and schemas to the point when removing anything would remove the error (a minimal sample)
- submit full sample to runkit.com and post the link here

Thank you

**Comment by DardanHaliti** [comment] 2019-10-25 19:22
Thank you for your time, here is the link.(It has some errors since runkit.com can not resolve the path), but i just want to see where the error is(or what am i doing wrong).
https://runkit.com/dardanhaliti/5db349872aa582001a2b676e

**Comment by epoberezkin** [comment] 2019-10-26 07:49
The error you get in runkit is different from the issue (and the same error as I expected): "Error: id "/path/to/file/schema2.json" resolves to more than one schema" - it fails on `ajv.addSchema(file1)`

It is because inside the first schema you have the same ID as used in the second schema (line 25 in runkit), Ajv does not allow it, as each ID needs to be unambiguous.

Please reproduce "call stack exceeded" in runkit.

**Comment by epoberezkin** [comment] 2020-02-17 07:05
@DardanHaliti going to close the issue as there is no sample that reproduces the error - please resubmit the issue with the full sample if it happens.

**Closed as completed by epoberezkin** 2020-02-17 07:05 UTC
Labels: missing info, bug report

**Comment by sijugeorge87** [comment] 2020-08-04 04:37
```javascript
  var schema_3 = {
    "$id": "http://aaaa.com/ssss/schema.json",
    "type": "object",
    "description": "An event generated by the participant interacting with an `Activity`.",
    "properties": {
      "time": {
        "$ref": "#/components/schemas/Time",
        "description": "The time when this event was created."
      },
      "datavalue": {
        "description": "The duration before recording ended.",
        "type": "integer",
        "format": "int64"
      },
      "activity": {
        "$ref": "#/components/schemas/Identification",
        "description": "The activity that produced this activity event."
      }
    }
  };
  
  
  var defsSchema_3 = {
    "$id": "http://aaaa.com/ssss/defs.json",
    "definitions": {
      "Time": { "type": "number"},  
      "Identification": { "type": "string"}
    }
  };
  
  
  var validate_3 = ajv.addSchema(defsSchema_3)
                    .compile(schema_3);
```

**i'm getting an error as below:**

{
  "error": "can't resolve reference #/components/schemas/Timefrom id http://aaaa.com/ssss/schema.json#"
}

Can anyone please check this and give me a solution?

**Comment by epoberezkin** [comment] 2020-08-04 07:36
@sijugeorge87 `"$ref": "#/components/schemas/Identification"` points to the non-existing location in the same schema

**Comment by DardanHaliti** [comment] 2020-08-04 14:36
You have to add the other schemas too ajv.addSchema(Schema1), ajv.addSchema(Schema2)... that have the ref tag. I can provide a code later if you still have the problem...
