### ISSUE TITLE
Assigning defaults for nested schema doesn't work

### ISSUE THREAD

**Issue by sabzDeveloper** [ajv-validator/ajv#1718] opened 2021-07-25 14:57 UTC
I tried this but it didn't work:
```

const ajv = new Ajv({ useDefaults: true })
  const schema = {
    type: 'object',
    properties: {
      foo: { type: 'number' },
      bar: {
        type: 'object',
        properties: {
          zoo: { type: 'string', default: 'deffff' },
        },
      },
    },
    required: ['foo', 'bar'],
  }

  const data = {}
  const validate = ajv.compile(schema)
  const valid = validate(data)
  console.log(data)
```

**Comment by epoberezkin** [comment] 2021-07-26 07:21
duplicate of https://github.com/ajv-validator/ajv/issues/1710

**Closed as completed by epoberezkin** 2021-07-26 07:21 UTC
Labels: usage
