### ISSUE TITLE
`removeAdditional` should only remove properties if the schema is valid

### ISSUE THREAD

**Issue by sberan** [ajv-validator/ajv#552] opened 2017-08-25 21:47 UTC
For the following schema, validation fails when `removeAdditional` is used. The issue is that the property `b` is removed when testing the first schema, and then the validation of the second schema fails because `b` no longer exists on the object. I propose that `removeAdditional` would only mutate the data if it passes validation. Thoughts?

```javascript
const Ajv = require('ajv')
const ajv = new Ajv({ allErrors: true, removeAdditional: true  })
const validate = ajv.compile({
  oneOf: [{
    properties: {
      a: { type: 'string' }
    },
    additionalProperties: false
  },{
    properties: {
      b: { type: 'string' }
    },
    additionalProperties: false
  }]
})
const data = { b: 'foo' }
console.log(validate(data)) // false
console.log(validate.errors[0].message) //  'should match exactly one schema in oneOf'
console.log(data) // {}
```

**Comment by epoberezkin** [comment] 2017-08-26 10:35
@sberan It's a duplicate of https://github.com/epoberezkin/ajv/issues/129 and many other [similar issues](https://github.com/epoberezkin/ajv/issues?q=is%3Aissue+removeadditional+is%3Aclosed).

Please review them and if you have something to add, comment there.

Also see [FAQ](https://github.com/epoberezkin/ajv/blob/master/FAQ.md#additional-properties-inside-compound-keywords-anyof-oneof-etc).

**Closed as completed by epoberezkin** 2017-08-26 10:35 UTC
Labels: duplicate
