### ISSUE TITLE
e.instancePath is undefined

### ISSUE THREAD

**Issue by dvnrsn** [ajv-validator/ajv#2292] opened 2023-06-14 16:46 UTC
```js
const validate = ajv.compile(jsonSchema)
validate(value)
validate[0].instancePath
```
There is however a schemaPath and a dataPath

<img width="531" alt="image" src="https://github.com/ajv-validator/ajv/assets/9112811/1b928bb0-9f84-418b-aa37-231e2a54182c">

The TS shows an `instancePath` and `schemaPath` but no `dataPath`

```js
export interface ErrorObject<K extends string = string, P = Record<string, any>, S = unknown> {
    keyword: K;
    instancePath: string;
    schemaPath: string;
```

**What version of Ajv are you using? Does the issue happen if you use the latest version?**

```
"ajv": "^8.12.0",
```

**Ajv options object**

**What results did you expect?**

TS types to match the actual data

**Are you going to resolve the issue?**

Happy to but wanted to see if I'm doing something wrong

**Comment by epoberezkin** [comment] 2023-07-29 09:03
it looks like you have data from a previous ajv version - impossible to say without sample code to reproduce.

**Comment by jasoniangreen** [comment] 2024-06-22 08:20
Closing as requested example code not provided.

**Closed as completed by jasoniangreen** 2024-06-22 08:20 UTC
Labels: typescript, missing info
