### ISSUE TITLE
Include additionalProperty name in error message

### ISSUE THREAD

**Issue by julien-f** [ajv-validator/ajv#1099] opened 2019-10-08 15:21 UTC
**What version of Ajv you are you using?**

`^6.10.0`

**What problem do you want to solve?**

```js
const ajv = new Ajv()
const validate = ajv.compile({
  type: 'object',
  additionalProperties: false,
  properties: {}
})
if (!validate({ foo: 0 })) {
  console.log(validate.errors[0].message)
}
```

I get: `should NOT have additional properties`.

**What do you think is the correct solution to problem?**

It should be nice to have the name of the additional property, like: `should NOT have additional property 'foo'`.

Is it possible? Did I miss something?

Is there a reason that's not the case?

**Will you be able to implement it?**

Maybe with some help :slightly_smiling_face:

**Comment by epoberezkin** [comment] 2019-10-08 18:04
Duplicate of #827 - please add there any comments if needed.

**Closed as completed by epoberezkin** 2019-10-08 18:04 UTC
Labels: duplicate
