### ISSUE TITLE
Typescipt and ESM yields "Ajv This expression is not constructable"

### ISSUE THREAD

**Issue by cyberwombat** [ajv-validator/ajv#2132] opened 2022-10-16 05:01 UTC
I have a TS project in ESM mode (type:module) and getting VSCode errors using certain modules such as Ajv..

Given this in my tsconfig.json:
```
{  
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "nodenext",
    "esModuleInterop": true
    // I had a lot more stuff but the top two lines are the ones causing issue (Node16 is same)
  }
}
```

package.json
```
{
  "name": "test",
  "type": "module",
  "dependencies": {
    "ajv": "^8.11.0"
  },

  "devDependencies": {
    "@tsconfig/node16": "^1.0.3",
    "@types/node": "^18.11.0",
    "typescript": "^4.8.3"
  }
}
```
and finally code:
```
import Ajv from "ajv"
export const getClient = ():Ajv => { 
  return  new Ajv()
}
```
I get the error as attached
<img width="856" alt="Screen Shot 2022-10-15 at 9 58 18 PM" src="https://user-images.githubusercontent.com/777498/196018875-a50b596c-330e-43d7-8ae9-61ba9fdc89bf.png">

Note that this code compiles correctly.

If I do:
```
import  Ajv from "ajv"
export const getClient = ():Ajv.default => { 
  return  new Ajv.default()
}
```
Then error goes away but it does not run.

I think this is something to do with CJS modules needing to add something for esm export but not sure exactly what. 

Here's a [sandbox](https://codesandbox.io/p/github/cyberwombat/ts-esm-test/draft/kind-sea?file=%2Findex.ts&workspace=%257B%2522activeFileId%2522%253A%2522cl9bh5ug20002lrhb6woealfc%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl9bh6bqv000blrhb74jv6h3z%2522%252C%2522key%2522%253A%2522cl9bh6b2o00523b6fhlt7a3mv%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by kachkaev** [comment] 2022-10-25 11:36
Same problem here in a ESM package. Here is a temp workaround:

```diff
-import Ajv from "ajv";
+import _Ajv from "ajv";
+
+const Ajv = _Ajv as unknown as typeof _Ajv.default;

const ajv = new Ajv();
```

**Comment by cyberwombat** [comment] 2022-10-25 14:41
@kachkaev that makes my VSCode errors go away but doesn't transpile when running Vitest - does it work for you and if so what test framework/settings?

**Comment by cyberwombat** [comment] 2022-10-25 15:14
@kachkaev that now gives me errors about `compile` and other methods not existing on ajv client

**Comment by kachkaev** [comment] 2022-10-25 15:48
Hmm not sure why that would be. I’m running an experiment in https://github.com/blockprotocol/blockprotocol/pull/709, things seem to work fine there. Well, if `_Ajv as unknown as typeof _Ajv.default` can be classified as ‘fine’ 😅

I’ve got `allowSyntheticDefaultImports` and `esModuleInterop` enabled in `tsconfig`, `moduleResolution` is equal to `NodeNext`. A few more CommonJS libs with a default export need the same hack.

**Comment by cyberwombat** [comment] 2022-10-25 15:54
My bad - I had the return type on the client creation set to `typeof Ajv` as per VS suggestion which was wrong.

**Comment by nicojs** [comment] 2023-05-06 21:14
This is also working for me:

```ts
import ajvModule from 'ajv';
const Ajv = ajvModule.default;
const ajv = new Ajv();
```

(no need for an `unknown` type assertion)

**Comment by benasher44** [comment] 2023-06-20 15:27
It looks like this is still an issue with the latest version. See https://arethetypeswrong.github.io/?p=ajv%408.12.0

**Comment by robcresswell** [comment] 2023-06-23 21:41
@nicojs Did that work at runtime? Its not the same as what @kachkaev wrote, which is just adjusting the types. You're actually assigning to default, rather than just forcing the type inference, which the link provided by @benasher44 indicates this is incorrect.

**Comment by nicojs** [comment] 2023-06-23 21:50
I'm always using `--esModuleInterop`, maybe that does the trick

**Comment by andrewbranch** [comment] 2023-07-27 16:46
> If I do:
>
> ```ts
> import  Ajv from "ajv"
> export const getClient = ():Ajv.default => { 
>   return  new Ajv.default()
> }
> ```
> Then error goes away but it does not run.

This _does_ run correctly in Node.js, as @nicojs pointed out. I don’t know of any runtime or bundler where it wouldn’t run. However, it’s probably not the API that AJV _intended_ to give to Node.js ESM users.

In the runtime CJS code, AJV uses a clever interop pattern:

```js
module.exports = exports = Ajv;
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Ajv;
```

that makes `Ajv` exposed both on `module.exports` and `module.exports.default`. So in reality, a Node ESM importer can do both of these:

```ts
// In Node, a default import always binds to the
// `module.exports` of a CJS module!
import Ajv from "ajv";
new Ajv();         // module.exports -> Ajv
new Ajv.default(); // module.exports.default -> Ajv
```

However, the types don’t reflect the existence of this interop pattern. The types just say

```ts
export default Ajv;
```

which implies that _only_ this part exists at runtime:

```js
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Ajv;
```

Which is why TypeScript is only going to let you access the symbol on `module.exports.default`:

```ts
import Ajv from "ajv";
new Ajv();
//  ^^^ The only thing you told me about the `module.exports` of "ajv"
//      is that it has a `default` property with an `Ajv` class.

new Ajv.default();
//  Yeah, now you’re constructing the class that you declared to exist.
```

To make the types more accurate, you should do something like this:

```ts
import AjvCore from "./core";
import { Format, FormatDefinition, AsyncFormatDefinition, KeywordDefinition, KeywordErrorDefinition, CodeKeywordDefinition, MacroKeywordDefinition, FuncKeywordDefinition, Vocabulary, Schema, SchemaObject, AnySchemaObject, AsyncSchema, AnySchema, ValidateFunction, AsyncValidateFunction, SchemaValidateFunction, ErrorObject, ErrorNoParams, } from "./types";
import { Plugin, Options, CodeOptions, InstanceOptions, Logger, ErrorsTextOptions } from "./core";
import { SchemaCxt, SchemaObjCxt } from "./compile";
import { KeywordCxt } from "./compile/validate";
import { DefinedError } from "./vocabularies/errors";
import { JSONType } from "./compile/rules";
import { JSONSchemaType } from "./types/json-schema";
import { _, str, stringify, nil, Name, Code, CodeGen, CodeGenOptions } from "./compile/codegen";
import { default as ValidationError } from "./runtime/validation_error";
import { default as MissingRefError } from "./compile/ref_error";
declare namespace Ajv {
  const _default: typeof Ajv;
  export { _default as default, Format, FormatDefinition, AsyncFormatDefinition, KeywordDefinition, KeywordErrorDefinition, CodeKeywordDefinition, MacroKeywordDefinition, FuncKeywordDefinition, Vocabulary, Schema, SchemaObject, AnySchemaObject, AsyncSchema, AnySchema, ValidateFunction, AsyncValidateFunction, SchemaValidateFunction, ErrorObject, ErrorNoParams, Plugin, Options, CodeOptions, InstanceOptions, Logger, ErrorsTextOptions, SchemaCxt, SchemaObjCxt, KeywordCxt, DefinedError, JSONType, JSONSchemaType, _, str, stringify, nil, Name, Code, CodeGen, CodeGenOptions, ValidationError, MissingRefError };
}
declare class Ajv extends AjvCore {
  _addVocabularies(): void;
  _addDefaultMetaSchema(): void;
  defaultMeta(): string | AnySchemaObject | undefined;
}
export = Ajv;
```

Notice that there’s now an `export = Ajv` instead of `export default Ajv`, but the namespace `Ajv` also has a `default` export/property with the same type.

**Comment by wjureczka** [comment] 2023-11-02 15:28
Any updates with version v8?

**Comment by fredsensibill** [comment] 2023-12-05 23:26
This still doesn't work. `ajv@8.12.0`

This is also not working for me:
```ts
import _Ajv from 'ajv';

const Ajv = _Ajv as unknown as typeof _Ajv.default;
const ajv = new Ajv();
```

I get an `error TS2339: Property 'default' does not exist on type 'typeof Ajv'.`

Only way I could make this work was with a `@ts-ignore`, unfortunately.

```ts
import _Ajv from 'ajv';

// @ts-ignore
const Ajv = _Ajv.default;
const ajv = new Ajv();
```

**Comment by cj-christoph-gysin** [comment] 2023-12-07 14:18
This could easily be fixed by providing named exports for `Ajv`, and then import those:
```
import { Ajv } from 'ajv';

const ajv = new Ajv();
```
The existing default export can be left untouched to avoid breaking any backwards compatibility. I'd be happy to make a PR for that.

**Comment by andrewbranch** [comment] 2023-12-07 17:43
FWIW, [my comment above](https://github.com/ajv-validator/ajv/issues/2132#issuecomment-1653983999) is PR-able and will fully fix the types. I didn’t PR it because I noticed that no meaningful changes have been made to this repo in a while, and I don’t use this library personally. But anyone else is welcome to copy/paste and ping me for review.

**Comment by benasher44** [comment] 2024-01-06 20:55
@andrewbranch I'm willing/ready to open a PR, but the changes you describe _I think_ only work if we can hand edit the .d.ts. In this case, the .d.ts is generated by TypeScript. I have so far been unsuccessful in writing a namespace in valid TypeScript that similarly re-exports the imports inside the namespace, like you suggested. I agree though that this does fix it, and I can verify the fixes work, when hand editing the .d.ts locally.

**Comment by andrewbranch** [comment] 2024-01-08 21:20
It looks like this will do the trick

```diff
class Ajv extends AjvCore {
+ static default = Ajv
  // ...
}

- module.exports = exports = Ajv
+ export = Ajv
Object.defineProperty(exports, "__esModule", {value: true})

- export default Ajv
- export {
-   Format,
-   FormatDefinition,
-   // ...
- } from "./types"

+ import * as types from "./types"
+ import * as core from "./core"
+ // ...

+ namespace Ajv {
+   export import Format = types.Format
+   export import FormatDefinition = types.FormatDefinition
+   // ...
+ }

**Comment by benasher44** [comment] 2024-01-08 22:01
Thanks for that! This gets very close. In resolve.ts, there's now an issue importing the Ajv class type.

Here's the import:

<img width="362" alt="image" src="https://github.com/ajv-validator/ajv/assets/1120429/fc32f195-1f18-40bf-91c4-3a62042d0205">

Here's an example usage:
<img width="943" alt="image" src="https://github.com/ajv-validator/ajv/assets/1120429/0f93e768-52ca-4236-8d32-597c14b20960">

**Comment by benasher44** [comment] 2024-01-08 22:03
Draft PR here: #2365

I'm not sure if there is a better way, but I ended up making named exports in two places to make their usages in `export import` easier.

**Comment by andrewbranch** [comment] 2024-01-08 22:54
How about instead of the `default` static property, we do this:

```diff
export = Ajv
Object.defineProperty(Ajv, "__esModule", {value: true})
+ Object.defineProperty(Ajv, "default", {value: Ajv})

+ declare namespace Ajv {
+   export { Ajv as default };
+ }
namespace Ajv {
  export import Format = types.Format
}
```

The issue is that the static property only confers a value meaning, not the type meaning of the `Ajv` class. Namespace exports, unlike properties, confer all meanings of the original symbol. But export declarations (`export { Ajv as default }`) aren’t allowed in real, non-ambient namespaces (for some reason), so we have to put it in an ambient one, and then take care of the value side in a way that TS isn’t paying attention to (`Object.defineProperty`). Not beautiful, but it should work.

**Comment by benasher44** [comment] 2024-01-08 23:12
Adding just that seems to work, but then I go remove the `static default` on the class, and I get this:

<img width="363" alt="image" src="https://github.com/ajv-validator/ajv/assets/1120429/2a11f7e3-1608-4fc7-ba67-669e631b314c">

**Comment by benasher44** [comment] 2024-01-08 23:13
And this for each of the `export import` in the non-ambient namespace (the ts error, not the eslint one):

<img width="521" alt="image" src="https://github.com/ajv-validator/ajv/assets/1120429/e9bcfa56-48b2-4590-b945-5a06dd1e5369">

**Comment by andrewbranch** [comment] 2024-01-08 23:31
That’s all eslint.

**Comment by benasher44** [comment] 2024-01-08 23:38
Whooops yes it lol 🤦

**Comment by benasher44** [comment] 2024-01-18 14:31
Published `@benasher44/ajv`, if folks want to give it a try

**Comment by piotr-cz** [comment] 2024-05-06 12:13
This has been fixed in v8.13 via https://github.com/ajv-validator/ajv/commit/f4a4c8ed742dd639fe2e70b33d740ca4d3c39c36:

```ts
import { Ajv } from 'ajv'
```

**Comment by mosoriorian** [comment] 2024-07-19 18:02
Maybe it is possible to close this issue with a reference to this PR: https://github.com/ajv-validator/ajv/pull/2389 ?

The issue should be resolved and we can now import Ajv as @piotr-cz mentioned

**Comment by jasoniangreen** [comment] 2024-07-21 09:51
Thanks for the heads up @mosoriorian and @piotr-cz and anyone else involved. Closing as fixed in https://github.com/ajv-validator/ajv/pull/2389

**Closed as completed by jasoniangreen** 2024-07-21 09:51 UTC
Labels: compatibility
