### ISSUE TITLE
JTDSchema with generics

### ISSUE THREAD

**Issue by NonSpicyBurrito** [ajv-validator/ajv#1658] opened 2021-06-23 06:05 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`8.6.0`. Yes.

**Your typescript code**

```typescript
import { JTDSchemaType } from 'ajv/dist/jtd'

type PropType = 'a' | 'b' | 'c'

type Obj<T extends PropType> = {
    type: T
}

// fails
function getObjSchema<T extends PropType>(propType: T): JTDSchemaType<Obj<T>> {
    return {
        properties: {
            type: { enum: [propType] },
        },
    }
}

// passes
function getObjSchemaA(propType: 'a'): JTDSchemaType<Obj<'a'>> {
    return {
        properties: {
            type: { enum: [propType] },
        },
    }
}
```

**Typescript compiler error messages**

```
Type '{ properties: { type: { enum: T[]; }; }; }' is not assignable to type 'JTDSchemaType<Obj<T>, Record<string, never>>'.
  Type '{ properties: { type: { enum: T[]; }; }; }' is not assignable to type '[undefined extends T ? never : "type"] extends [never] ? { properties?: Record<string, never> | undefined; } : { properties: { [K in undefined extends T ? never : "type"]: JTDSchemaType<Obj<T>[K], Record<...>>; }; }'.ts(2322)
```

**Describe the change that should be made to address the issue?**
Not sure.

**Are you going to resolve the issue?**
No.

**Comment by epoberezkin** [comment] 2021-06-24 07:02
I don't think the problem here is how JTDSchemaType is defined. The problem here fundamentally is that `T extends PropType` can include more than one value from PropType definition, and the schema is defined to allow only exactly one value - so it indeed does not match your data type.

cc @erikbrinkman

**Comment by NonSpicyBurrito** [comment] 2021-06-24 07:27
> I don't think the problem here is how JTDSchemaType is defined. The problem here fundamentally is that `T extends PropType` can include more than one value from PropType definition, and the schema is defined to allow only exactly one value - so it indeed does not match your data type.
> 
> cc @erikbrinkman

How should I go about typing the `getObjSchema` function then? Intuitively I thought how I typed it was the way to go.

**Comment by erikbrinkman** [comment] 2021-06-25 03:15
@epoberezkin is right. What you want is impossible due to the definition of the JTD schema. `JTDSchemaType<T>` is invariant of `T`, meaning, if `S` is assignable to `T`, that doesn't mean that `JTDSchemaType<S>` is assignable to `JTDSchemaType<T>`. The clearest example is `PropType` is assignable to `string`, but `JTDSchemaType<PropType>` is not assignable to `JTDSchemaType<string>`. In your specific example this shows up with `never`. `never` is a valid parameter of the function, but your result is not assignable to `JTDSchemaType<Obj<never>>`.

As to how you should fix it, typescript is actually pretty handy here. Typescript types are structural, meaning you don't actually need to declare the type to be `JSONSchemaType` you just need it to be assignable to a JSONSchemaType. In this specific example you could do something like this:
```typescript
type MySchema<T extends PropType> = {
    properties: {
        type: {
            enum: T[]
        }
    }
}

// passes
function getObjMySchema<T extends PropType>(propType: T): MySchema<T> {
    return {
        properties: {
            type: { enum: [propType] },
        },
    }
}

const myASchema: JTDSchemaType<Obj<'a'>> = getObjMySchema<'a'>('a');
const myBCSchema: JTDSchemaType<Obj<'b' | 'c'>> = getObjMySchema<'b' | 'c'>('b');
```

The key here is that `MySchema` isn't a complicated conditional type, and is instead covariant in T, which is what you need to make your function correct. However, afterwards, you can still assign to a concrete `JTDSchemaType`. Unfortunately, this will still require manual annotation 😢. I don't think there's ultimately a way around that, again due to the invariance of the type / definition.

**Comment by NonSpicyBurrito** [comment] 2021-06-25 11:52
@erikbrinkman Thanks, your solution does work, and I've come to understand the issue at its core thanks to the excellent explanations above.

However it does make it not as nice to use:
- Schema needs to be typed out twice, once in the type definition and another time in the function body.
- It introduces an intermediate type that serves no purpose other than to circumvent the issue.
- You lose the autocomplete comparing to using `JTDSchemaType<Obj<T>>`, which is especially problematic for a large object.

I found that the best way to work with this solution, is to implement `function getObjSchemaA(propType: 'a'): JTDSchemaType<Obj<'a'>>` first so I get autocomplete while coding it, turn it into generic version, and lastly extract the type with copy pasting.

It might be a bit minor and feel a bit nitpicky, but I wonder if there's a better way to go. If that's the best solution we have, then I'll close this issue.

**Comment by erikbrinkman** [comment] 2021-06-25 13:10
I agree it's inelegant. Whether to close it is potentially up to @epoberezkin. I think from the definition of JTD Schema, the type itself has to be invariant, which as stated above, is the root cause, and therefore unfixable. There may be ways to create a type that's less strict that is covariant, but I think that's probably not feasible with the same guarantees.

The other avenue I see is `JTDDataType`. This infers the resulting type from the schema type instead of requiring annotation of the schema itself. Going off of my example above, you can do something like:
```typescript
const myASchemaData = getObjMySchema<'a'>('a');
type MyAResult = JTDDataType<typeof myASchema>
```
`MyResult` here is structurally equivalent to `Obj<'a'>`.  Ideally if you specify the type of `getObjMySchema` correctly, then you should be fine. `ajv` should infer a proper validated type from it. `avj` has some trouble with inference due to the complexity of the overloads, but this more complicated version also worked with a simpler stubbed out validate:
```typescript
declare function validate<T extends SomeJTDSchemaType>(schema: T, obj: unknown): JTDDataType<T>;

function myValidate<T extends PropType>(propType: T, obj: unknown): JTDDataType<MySchema<T>> {
  const schema = getObjMySchema(propType);
  const result = validate(schema, obj);
  return result;
}

const aObj: Obj<'a'> = myValidate('a', null);
```
here the type declaration at the end isn't necessary, it's a validation that the result of `myValidate` is actually assignable to `Obj<'a'>`.

**Closed as completed** 2021-06-26 08:33 UTC
Labels: typescript
