### ISSUE TITLE
ajv 2019: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by asibilia** [ajv-validator/ajv#1380] opened 2021-01-05 00:14 UTC
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
`7.0.3` - Yes

**Ajv options object**

```javascript
export const ajv = new Ajv({
  allErrors: true,
  useDefaults: "empty",
  $data: true,
  strict: false
});

ajv.addKeyword({
  keyword: "isNotEmpty",
  validate: (_schema: any, data: any) => !isEmpty(data),
  errors: false
});
```

**JSON Schema**

```json
{
    "type": "object",
    "properties": {
      "country_of_birth": {
        "type": "string",
        "enum": ["USA", "Other"]
      },
      "ssn": {
        "type": "string",
      },
      "confirm_ssn": {
        "type": "string",
      },
      "tax_id": {
        "type": "string"
      },
      "confirm_tax_id": {
        "type": "string"
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "country_of_birth": {
              "const": "Other"
            }
          }
        },
        "then": {
          "allOf": [
            {
              "if": {
                "properties": {
                  "confirm_tax_id": {
                    "isNotEmpty": true
                  }
                }
              },
              "then": {
                "properties": {
                  "tax_id": {
                    "isNotEmpty": true
                  }
                }
              }
            },
            {
              "if": {
                "properties": {
                  "tax_id": {
                    "isNotEmpty": true
                  }
                }
              },
              "then": {
                "properties": {
                  "confirm_tax_id": {
                    "isNotEmpty": true
                  }
                }
              }
            }
          ]
        }
      },
      {
        "if": {
          "properties": {
            "country_of_birth": {
              "const": "USA"
            }
          }
        },
        "then": {
          "allOf": [
            {
              "if": {
                "properties": {
                  "confirm_ssn": {
                    "isNotEmpty": true
                  }
                }
              },
              "then": {
                "properties": {
                  "ssn": {
                    "isNotEmpty": true
                  }
                }
              }
            },
            {
              "if": {
                "properties": {
                  "ssn": {
                    "isNotEmpty": true
                  }
                }
              },
              "then": {
                "properties": {
                  "confirm_ssn": {
                    "isNotEmpty": true
                  }
                }
              }
            }
          ]
        }
      }
    ]
  }
```

**Sample data**

```json
{
   "country_of_birth": "USA",
   "ssn": "1",
   "confirm_ssn": "1",
}
```

**Your code**

Here's a sandbox to test the issue: https://codesandbox.io/s/form-generator-test-bug-07368?file=/src/App.tsx

**What results did you expect?**
I expect the form to work properly for both `country_of_birth` values. Instead what you see is if you change `country_of_birth` to `USA` and try to validate both `ssn` and `confirm_ssn` fields, an error is thrown. This behavior does not happen if you set `country_of_birth` to `Other` (which will trigger the validation on `tax_id`/`confirm_tax_id` rather than `ssn`).

In `src/form-generator/helpers.ts` If you change the import from `ajv/dist/2019` to `ajv` you will not see the error. Also, if you change the order of the `allOf` array items it will change which fields throw the error.

**Are you going to resolve the issue?**
No

**Comment by epoberezkin** [comment] 2021-01-06 14:00
The example is a bit too big to be certain, but the issue is likely to be that if the property is absent (or undefined) the keywords for this property will not be applied. You need to use "required" keyword and instead of if/then you can use "dependencies" keyword.

Please submit a smaller failing example if the issue is something else, so it is clear what exactly is wrong.

**Comment by epoberezkin** [comment] 2021-01-19 21:13
closing here, please submit another issue with a smaller example if needed...

**Closed as completed by epoberezkin** 2021-01-19 21:13 UTC
Labels: missing info, bug report
